# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Chad M. Eliason
tagline:             'Bass Postdoctoral Fellow, Field Museum of Natural History'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# Google services
google_analytics: UA-85421317-1

# About/contact
author:
  name:              Chad Eliason
  url:               https://twitter.com/mdo
  email:             celiason@fieldmuseum.org

# Custom vars
version:             1.0.0


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
