# Site settings
title: Chad M. Eliason
email: chad_eliason@utexas.edu
description: > # this means to ignore newlines until "baseurl:"

# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://celiason.github.io" # the base hostname & protocol for your site
# twitter_username: JAlexBranham
github_username:  celiason
# permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
