# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            chad eliason
tagline:          'evolutionary biologist'
description:      'Evolutionary biologist at the University of Texas at Austin'
url:              http://celiason.github.io

author:
  name:           'Chad Eliason'
  url:            na

# paginate:         5

github:
  repo:           https://github.com/mwpennell/mwpennell.github.io

